### ISSUE TITLE
Deinitializer is missing

### ISSUE THREAD

**Issue by nvdl** [GENIVI/capicxx-someip-runtime#1]
The de-initializer is missing in:

https://github.com/GENIVI/capicxx-someip-runtime/blob/64f0cb0133b23ff13c48c377546cdaef45b3d9ce/src/CommonAPI/SomeIP/Factory.cpp#L23

Adding to "Types.hpp" fixes the issue:

`#define DEINITIALIZER(f) \
    static void f(void) __attribute__((destructor)); \
    static void f(void)`

I do not know if this is the correct approach though.

**Comment by lutzbichler** [comment]
DEINITIALIZER (and INITIALIZER) are defined in capicxx-core-runtime, Types.hpp.
