### ISSUE TITLE
Does the commonapi-someip support the latest vsomeip3?

### ISSUE THREAD

**Issue by rlokanathan** [GENIVI/capicxx-someip-runtime#12]
Hi,

My current setup is using:

boost: 1.67
vsomeip3

I am not able to compile the commonapi-someip application using vsomeip3. I am not sure whether are there any dependencies issues? Or the current commonapi-someip doesnt support vsomeip3? Because when i tried to compile using vsomeip2 it works fine.

**Comment by lutzbichler** [comment]
Starting with 3.2.0 it does. Before you need to enable the vSomeIP compatibility layer (-DENABLE_COMPAT=1) when building vSomeIP.
